/*
 * Copyright Notice:
 *      Copyright  1998-2008, Huawei Technologies Co., Ltd.  ALL Rights Reserved.
 *
 *      Warning: This computer software sourcecode is protected by copyright law
 *      and international treaties. Unauthorized reproduction or distribution
 *      of this sourcecode, or any portion of it, may result in severe civil and
 *      criminal penalties, and will be prosecuted to the maximum extent
 *      possible under the law.
 */
package com.huawei.iom.nademo.common.consts;

public class CommonConst {

    public static final Long REGISTER_URL_MAX_PERIOD = 64000L;
    public static final Long REGISTER_URL_MIN_PERIOD = 1000L;
    public static final Long SECOND_TO_MILLISECOND = 1000L;

    //网关和传感器数据上报的常量
    public static final String NOTIFY_TYPE_UPDATE_DEVICE = "updateDevice";
    public static final String NOTIFY_TYPE_DELETE_SENSOR = "deleteSensor";
    public static final String NOTIFY_TYPE_ADD_SENSOR    = "addSensor";
    public static final String NOTIFY_TYPE_DELETE_DEVICE = "deleteDevice";

    // notify type generated by NSCL
    public static final String NOTIFY_TYPE_ACTIVE_DEVICE = "bindDevice";
    public static final String NOTIFY_TYPE_ADD_DEVICE = "deviceAdded";
    public static final String NOTIFY_TYPE_DROP_DEVICE = "deviceDeleted";
    public static final String NOTIFY_TYPE_UPDATE_DEVICEINFO = "deviceInfoChanged";
    public static final String NOTIFY_TYPE_UPDATE_DEVICEDATA = "deviceDataChanged";
    public static final String NOTIFY_TYPE_UPDATE_SERVICEINFO = "serviceInfoChanged";
    public static final String NOTIFY_TYPE_MESSAGE_CONFIRM = "messageConfirm";
    public static final String NOTIFY_TYPE_COMMAND_RSP = "commandRsp";
    public static final String NOTIFY_TYPE_DEVICE_EVENT = "deviceEvent";

    // 接入设备类型, 分为网关类型设备和普通设备
    public static final String DEVICE_NODETYPE_GATEWAY = "GATEWAY";
    public static final String DEVICE_NODETYPE_ENDPOINT = "ENDPOINT";

}
